# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad8ed4dd1f0696e17af1e79d851e219a2b85c66b4ca17ab0212fc63c5d90418b941cac7a6b060d8f9e0182697143a9addb40abded0966a4ccac1738916525ee8

test:
  secret_key_base: 1f278c237569a1d3ffdbece68f6742e8122c3e7ae17bacb01600bbf0fff01eef9bb03a175e624d35b9bb43afae32c68f1ed2b9e23bcd794306b42a84e3fa7459

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
